Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    # Configurar ip estatico
    # config.vm.network "private_network", ip: "192.168.56.17"
    # Configurar ip dinamico
    config.vm.network "public_network", bridge: "en0: Ethernet"
    
    # Sincronizar diretórios
    config.vm.synced_folder "./scripts", "/opt/scripts"

    # Configurar especs da VM
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 2
    
    end

    # Executar shell na VM e rodar um trecho de comandos
    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y apache2
    SHELL

end